version: "3.8"

services:
  rails_app:
    container_name: rails_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
    restart: always
    entrypoint: ./entrypoints/docker-entrypoint.sh

  db:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
