---
openapi: 3.0.1
info:
  title: Academic Assessment
  description: Building application for performance academic.
  version: v1
  x-author: Lucas Alves
paths:
  "/api/v1/grades":
    post:
      summary: Create a new grade
      tags:
      - Grades
      parameters: []
      responses:
        '201':
          description: created
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                student_id:
                  type: string
                  description: Student ID
                discipline_id:
                  type: string
                  description: Discipline ID
                value:
                  type: number
                  description: Value (e.g., 0-100)
              required:
              - student_id
              - discipline_id
              - value
  "/api/v1/grades/students/{id}":
    get:
      summary: Get grades and final grade for a student
      tags:
      - Grades
      parameters:
      - name: id
        in: path
        description: Student ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      grades:
                        type: array
                        items:
                          type: object
                      final_grade:
                        type: number
        '404':
          description: not found
  "/api/v1/histories/students/{id}":
    parameters:
    - name: id
      in: path
      description: Student ID
      required: true
      schema:
        type: string
    get:
      summary: Get histories for a student
      tags:
      - Histories
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: History ID
                        final_grade:
                          type: number
                          format: float
                          description: Final grade
                        reference_date:
                          type: string
                          format: date
                          description: Reference date
                        created_at:
                          type: string
                          format: date_time
                          description: Created_at
                        updated_at:
                          type: string
                          format: date_time
                          description: Updated_at
                        student:
                          type: object
                          properties:
                            id:
                              type: string
                              description: Student ID
                            name:
                              type: string
                              description: Name
                            created_at:
                              type: string
                              format: date_time
                              description: Created_at
                            updated_at:
                              type: string
                              format: date_time
                              description: Updated_at
        '404':
          description: not found
  "/api/v1/students":
    get:
      summary: List top students
      tags:
      - Students
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: History ID
                        final_grade:
                          type: number
                          format: float
                          description: Final grade
                        reference_date:
                          type: string
                          format: date
                          description: Reference date
                        created_at:
                          type: string
                          format: date_time
                          description: Created_at
                        updated_at:
                          type: string
                          format: date_time
                          description: Updated_at
                        student:
                          type: object
                          properties:
                            id:
                              type: string
                              description: Student ID
                            name:
                              type: string
                              description: Name
                            created_at:
                              type: string
                              format: date_time
                              description: Created_at
                            updated_at:
                              type: string
                              format: date_time
                              description: Updated_at
        '404':
          description: not found
  "/api/v1/student":
    get:
      summary: Get student closest to maximum grade (100)
      tags:
      - Students
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Student ID
                      name:
                        type: string
                        description: Student Name
                      final_grade:
                        type: number
                        format: float
                        description: Final grade
        '404':
          description: no students found
servers:
- url: http://localhost:3000
